### ISSUE TITLE
Members page Items per page gets bugged

### ISSUE THREAD

**Issue by KKlimentov1618** [ccims/ccims-frontend#73]
Scenario: Items per page is set to 3
and there are 6 users overall (User 1, ..., User6).

- When adding a new user (ex. AddedUser1) all 7 users
(aka. User1, ..., User6, AddedUser1) become visible
even though Items per page is still set to 3.
Also, the Items per page settings stop working entirely and 
the page needs to be reloaded.

- When removing a user (ex. User1) all 5 users
(aka. User2, ..., User6) become visible
...

**Comment by Kristinapn** [comment]
this issue is identical with the list sorting issue (waiting on backend)
